export const teams = {
    "HoangAnhGiaLai": {
        "idteam":1,
        "clubName": "LPBank Hoàng Anh Gia Lai",
        "logo": "https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg",
        "stadium": "SVD Bình Dương (Sức chứa: 15.000 người)",
        "coach": "Trần Lê Anh Khoa",
        "players": [ 
  {
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "180",
    "weight": "79",
    "position": "GK",
    "nationality": "VIE",
    "kit": "26",
    "achievement": "",
    "name": "Huỳnh Tuấn Linh",
    "birthDay": "1991-04-12",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "Naturalization Player",
    "height": "185",
    "weight": "81",
    "position": "ST",
    "nationality": "BRA",
    "kit": "92",
    "achievement": "",
    "name": "Bruno Henrique",
    "birthDay": "1992-10-25",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "191",
    "weight": "82",
    "position": "GK",
    "nationality": "VIE",
    "kit": "25",
    "achievement": "",
    "name": "Trần Trung Kiên",
    "birthDay": "2003-02-09",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "167",
    "weight": "67",
    "position": "MF",
    "nationality": "VIE",
    "kit": "8",
    "achievement": "",
    "name": "Trần Minh Vương",
    "birthDay": "1995-03-28",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "169",
    "weight": "66",
    "position": "DF",
    "nationality": "VIE",
    "kit": "7",
    "achievement": "",
    "name": "Nguyễn Phong Hồng Duy",
    "birthDay": "1996-06-13",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "174",
    "weight": "62",
    "position": "MF",
    "nationality": "VIE",
    "kit": "34",
    "achievement": "",
    "name": "Lê Hữu Phước",
    "birthDay": "2001-05-07",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "Naturalization Player",
    "height": "198",
    "weight": "94",
    "position": "DF",
    "nationality": "BRA",
    "kit": "94",
    "achievement": "",
    "name": "Barbosa Teixeira Mauricio",
    "birthDay": "1994-12-08",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "170",
    "weight": "58",
    "position": "ST",
    "nationality": "VIE",
    "kit": "9",
    "achievement": "",
    "name": "Nguyễn Văn Toàn",
    "birthDay": "1996-04-12",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "177",
    "weight": "75",
    "position": "DF",
    "nationality": "VIE",
    "kit": "28",
    "achievement": "",
    "name": "Nguyễn Văn Việt",
    "birthDay": "1989-01-17",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "168",
    "weight": "65",
    "position": "ST",
    "nationality": "VIE",
    "kit": "10",
    "achievement": "",
    "name": "Nguyễn Công Phượng",
    "birthDay": "1995-01-21",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "180",
    "weight": "74",
    "position": "DF",
    "nationality": "VIE",
    "kit": "12",
    "achievement": "",
    "name": "Tiêu Ê Xal",
    "birthDay": "2000-08-14",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "178",
    "weight": "72",
    "position": "MF",
    "nationality": "VIE",
    "kit": "6",
    "achievement": "",
    "name": "Lương Xuân Trường",
    "birthDay": "1995-04-28",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "168",
    "weight": "65",
    "position": "DF",
    "nationality": "VIE",
    "kit": "23",
    "achievement": "",
    "name": "Nguyễn Thanh Nhân",
    "birthDay": "2000-10-25",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "169",
    "weight": "68",
    "position": "MF",
    "nationality": "VIE",
    "kit": "60",
    "achievement": "",
    "name": "Võ Đình Lâm",
    "birthDay": "2000-01-10",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "188",
    "weight": "73",
    "position": "MF",
    "nationality": "VIE",
    "kit": "27",
    "achievement": "",
    "name": "Nguyễn Văn Triệu",
    "birthDay": "2003-01-17",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "Naturalization Player",
    "height": "186",
    "weight": "80",
    "position": "MF",
    "nationality": "KR",
    "kit": "40",
    "achievement": "",
    "name": "An Sae Hee",
    "birthDay": "1991-02-08",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "169",
    "weight": "63",
    "position": "ST",
    "nationality": "VIE",
    "kit": "20",
    "achievement": "",
    "name": "Trần Bảo Toàn",
    "birthDay": "2000-07-14",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "Naturalization Player",
    "height": "183",
    "weight": "83",
    "position": "ST",
    "nationality": "BRA",
    "kit": "30",
    "achievement": "",
    "name": "Washington Brandão Dos Santos",
    "birthDay": "1990-08-18",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "174",
    "weight": "70",
    "position": "MF",
    "nationality": "VIE",
    "kit": "24",
    "achievement": "",
    "name": "Nguyễn Đức Việt",
    "birthDay": "2004-01-01",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "172",
    "weight": "73",
    "position": "DF",
    "nationality": "VIE",
    "kit": "17",
    "achievement": "",
    "name": "Vũ Văn Thanh",
    "birthDay": "1996-04-14",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "168",
    "weight": "65",
    "position": "MF",
    "nationality": "VIE",
    "kit": "21",
    "achievement": "",
    "name": "Lê Huy Kiệt",
    "birthDay": "2003-10-20",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "170",
    "weight": "70",
    "position": "DF",
    "nationality": "VIE",
    "kit": "5",
    "achievement": "",
    "name": "Trần Hữu Đông Triều",
    "birthDay": "1995-08-20",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "178",
    "weight": "70",
    "position": "DF",
    "nationality": "VIE",
    "kit": "15",
    "achievement": "",
    "name": "Nguyễn Hữu Tuấn",
    "birthDay": "1992-05-06",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "169",
    "weight": "64",
    "position": "DF",
    "nationality": "VIE",
    "kit": "2",
    "achievement": "",
    "name": "Lê Văn Sơn",
    "birthDay": "1996-12-20",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "172",
    "weight": "60",
    "position": "ST",
    "nationality": "VIE",
    "kit": "47",
    "achievement": "",
    "name": "Cao Hoàng Tú",
    "birthDay": "2001-06-09",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "175",
    "weight": "66",
    "position": "MF",
    "nationality": "VIE",
    "kit": "11",
    "achievement": "",
    "name": "Nguyễn Tuấn Anh",
    "birthDay": "1995-05-16",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "174",
    "weight": "67",
    "position": "MF",
    "nationality": "VIE",
    "kit": "82",
    "achievement": "",
    "name": "A Hoàng",
    "birthDay": "1995-07-31",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "177",
    "weight": "73",
    "position": "GK",
    "nationality": "VIE",
    "kit": "1",
    "achievement": "",
    "name": "Dương Văn Lợi",
    "birthDay": "2000-12-02",
    "status": ""
},
{
    "clubName": "LPBank Hoàng Anh Gia Lai",
    "seaSon": "2023-2024",
    "typePlayer": "National Player",
    "height": "169",
    "weight": "63",
    "position": "ST",
    "nationality": "VIE",
    "kit": "22",
    "achievement": "",
    "name": "Nguyễn Nhĩ Khang",
    "birthDay": "2001-02-16",
    "status": ""
}
]
    }

};
