export const Rankdata2023 = [
  {
    sumid: 1,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/5/5a/Logo_of_S%C3%B4ng_Lam_Ngh%E1%BB%87_An.svg/1200px-Logo_of_S%C3%B4ng_Lam_Ngh%E1%BB%87_An.svg.png",
    teamname: "Sông Lam Nghệ An",
    play: 20,
    win: 14,
    draw: 4,
    lost: 2,
    GF: 30,
    GA: 20,
  },
  {
    sumid: 2,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg",
    teamname: "LPBank Hoàng Anh Gia Lai",
    play: 20,
    win: 14,
    draw: 4,
    lost: 2,
    GF: 40,
    GA: 25,
    idteam:1,
  },
  {
    sumid: 3,
    image: "https://upload.wikimedia.org/wikipedia/vi/3/30/Ha_Noi_FC_logo_%28no_star%29.png",
    teamname: "Hà Nội FC",
    play: 20,
    win: 11,
    draw: 6,
    lost: 3,
    GF: 38,
    GA: 22,
  },
  {
    sumid: 4,
    image: "https://upload.wikimedia.org/wikipedia/vi/c/cb/Logo_Becamex_B%C3%ACnh_D%C6%B0%C6%A1ng_2021.png",
    teamname: "Becamex Bình Dương",
    play: 20,
    win: 10,
    draw: 5,
    lost: 5,
    GF: 35,
    GA: 27,
  },
  {
    sumid: 5,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/8/89/Nam_%C4%90%E1%BB%8Bnh_FC_logo.svg/800px-Nam_%C4%90%E1%BB%8Bnh_FC_logo.svg.png",
    teamname: "Thép Xanh Nam Định",
    play: 20,
    win: 9,
    draw: 6,
    lost: 5,
    GF: 33,
    GA: 28,
  },
  {
    sumid: 6,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/3/38/Logo_CAHN_FC.svg/800px-Logo_CAHN_FC.svg.png",
    teamname: "Công An Hà Nội",
    play: 20,
    win: 13,
    draw: 4,
    lost: 3,
    GF: 52,
    GA: 30,
  },
  {
    sumid: 7,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/5/51/Logo_CLB_TPHCM.svg/440px-Logo_CLB_TPHCM.svg.png?20230129044612",
    teamname: "TP Hồ Chí Minh",
    play: 19,
    win: 15,
    draw: 3,
    lost: 1,
    GF: 45,
    GA: 28,
  },
  {
    sumid: 8,
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsHJR6rkXFSSTbinY8nGc-R77BZo_4HGIawJCEYFGMZA&s",
    teamname: "MerryLand Quy Nhơn Bình Định",
    play: 20,
    win: 5,
    draw: 7,
    lost: 8,
    GF: 20,
    GA: 28,
  },
  {
    sumid: 9,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/0/03/Logo_CLB_DATH.svg/1200px-Logo_CLB_DATH.svg.png",
    teamname: "Đông Á Thanh Hóa",
    play: 20,
    win: 13,
    draw: 6,
    lost: 1,
    GF: 55,
    GA: 26,
  },
  {
    sumid: 10,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/2/21/H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg/1200px-H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg.png",
    teamname: "Hải Phòng",
    play: 20,
    win: 11,
    draw: 1,
    lost: 8,
    GF: 42,
    GA: 36,
  },
  {
    sumid: 11,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/2/21/H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg/1200px-H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg.png",
    teamname: "Hồng Lĩnh Hà Tĩnh",
    play: 20,
    win: 8,
    draw: 6,
    lost: 6,
    GF: 37,
    GA: 28,
  },
  {
    sumid: 12,
    image: "https://upload.wikimedia.org/wikipedia/vi/2/25/Qu%E1%BA%A3ng_Nam_FC.svg",
    teamname: "Quảng Nam",
    play: 20,
    win: 11,
    draw: 4,
    lost: 5,
    GF: 39,
    GA: 22,
  },
  {
    sumid: 13,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/8/80/Logo_CLB_TC-VT.svg/1200px-Logo_CLB_TC-VT.svg.png",
    teamname: "Thể Công – Viettel",
    play: 20,
    win: 12,
    draw: 2,
    lost: 6,
    GF: 37,
    GA: 25,
  },
  {
    sumid: 14,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/4/49/Kh%C3%A1nh_H%C3%B2a_FC_2021.svg/1200px-Kh%C3%A1nh_H%C3%B2a_FC_2021.svg.png",
    teamname: "Khánh Hòa",
    play: 20,
    win: 5,
    draw: 7,
    lost: 8,
    GF: 20,
    GA: 34,
  },
];
export const Rankdata2022 = [
  {
    sumid: 1,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/5/5a/Logo_of_S%C3%B4ng_Lam_Ngh%E1%BB%87_An.svg/1200px-Logo_of_S%C3%B4ng_Lam_Ngh%E1%BB%87_An.svg.png",
    teamname: "Sông Lam Nghệ An",
    play: 20,
    win: 13,
    draw: 5,
    lost: 2,
    GF: 42,
    GA: 18,
  },
  {
    sumid: 2,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg",
    teamname: "Hoàng Anh Gia Lai",
    play: 20,
    win: 15,
    draw: 3,
    lost: 2,
    GF: 38,
    GA: 24,
  },
  {
    sumid: 3,
    image: "https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg",
    teamname: "Hà Nội FC",
    play: 20,
    win: 10,
    draw: 7,
    lost: 3,
    GF: 36,
    GA: 21,
  },
  {
    sumid: 4,
    image: "https://upload.wikimedia.org/wikipedia/vi/c/cb/Logo_Becamex_B%C3%ACnh_D%C6%B0%C6%A1ng_2021.png",
    teamname: "Becamex Bình Dương",
    play: 20,
    win: 9,
    draw: 6,
    lost: 5,
    GF: 34,
    GA: 26,
  },
  {
    sumid: 5,
    image: "https://upload.wikimedia.org/wikipedia/vi/thumb/a/a6/Logo_H%C3%B2a_B%C3%ACnh_FC.png/200px-Logo_H%C3%B2a_B%C3%ACnh_FC.png",
    teamname: "Hòa Bình",
    play: 20,
    win: 8,
    draw: 7,
    lost: 5,
    GF: 30,
    GA: 27,
  },
];
