export const DataPlayers ={
"data": [
        {   
            "PlayerId": 1,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "180",
            "weight": "79",
            "position": "GK",
            "nationality": "VIE",
            "kit": "26",
            "achievement": "",
            "name": "Huỳnh Tuấn Linh",
            "birthDay": "1991-04-12",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/z4869696356921_ea0bfc2b3262bce4069609434458e0aa-310x413.jpg"
        },
        {   
            "PlayerId": 2,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "Naturalization Player",
            "height": "185",
            "weight": "81",
            "position": "ST",
            "nationality": "BRA",
            "kit": "92",
            "achievement": "",
            "name": "Bruno Henrique",
            "birthDay": "1992-10-25",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2020/01/HAGL-92-Bruno-Henrique-De-Sousa.jpg"
        },
        {   
            "PlayerId": 3,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "191",
            "weight": "82",
            "position": "GK",
            "nationality": "VIE",
            "kit": "25",
            "achievement": "",
            "name": "Trần Trung Kiên",
            "birthDay": "2003-02-09",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_25_TranTrungKien_VN0000782.jpg"
        },
        {
            "PlayerId": 4,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "167",
            "weight": "67",
            "position": "MF",
            "nationality": "VIE",
            "kit": "8",
            "achievement": "",
            "name": "Trần Minh Vương",
            "birthDay": "1995-03-28",
            "status": "",
            "PlayerImg":"https://vpf.vn/wp-content/uploads/2018/12/HAGL_10_TranMinhVuong_VN0001154.jpg"
        },
        {   
            "PlayerId": 5,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "169",
            "weight": "66",
            "position": "DF",
            "nationality": "VIE",
            "kit": "7",
            "achievement": "",
            "name": "Nguyễn Phong Hồng Duy",
            "birthDay": "1996-06-13",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/NDFC_VN0002244_NguyenPhongHongDuy_7-310x421.jpg"
        },
        {
            "PlayerId": 6,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "174",
            "weight": "62",
            "position": "MF",
            "nationality": "VIE",
            "kit": "34",
            "achievement": "",
            "name": "Lê Hữu Phước",
            "birthDay": "2001-05-07",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2021/03/HAGL_18_LeHuuPhuoc_VN0001166-310x414.jpg"
        },
        {   "PlayerId": 7,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "Naturalization Player",
            "height": "198",
            "weight": "94",
            "position": "DF",
            "nationality": "BRA",
            "kit": "94",
            "achievement": "",
            "name": "Barbosa Teixeira Mauricio",
            "birthDay": "1994-12-08",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_BR0000466_BARBOSATEIXEIRAMAURICIO_94.jpg"
        },
        {   "PlayerId": 8,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "170",
            "weight": "58",
            "position": "ST",
            "nationality": "VIE",
            "kit": "9",
            "achievement": "",
            "name": "Nguyễn Văn Toàn",
            "birthDay": "1996-04-12",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2020/01/HPFC_26_NguyenVanToan_VN0000281-310x466.jpg"
        },
        {   
            "PlayerId": 9,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "177",
            "weight": "75",
            "position": "DF",
            "nationality": "VIE",
            "kit": "28",
            "achievement": "",
            "name": "Nguyễn Văn Việt",
            "birthDay": "1989-01-17",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/SLNA_14_NguyenVanViet_VN001829-310x466.jpg"
        },
        {   
            "PlayerId": 10,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "168",
            "weight": "65",
            "position": "ST",
            "nationality": "VIE",
            "kit": "10",
            "achievement": "",
            "name": "Nguyễn Công Phượng",
            "birthDay": "1995-01-21",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/VTFC_6_NguyenCongPhuong_VN001868-310x413.jpg"
        },
        {
            "PlayerId": 11,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "180",
            "weight": "74",
            "position": "DF",
            "nationality": "VIE",
            "kit": "12",
            "achievement": "",
            "name": "Tiêu Ê Xal",
            "birthDay": "2000-08-14",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2020/02/BRVT_33_TieuEXal_VN0002261-310x413.jpg"
        },
        {   
            "PlayerId": 12,    
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "178",
            "weight": "72",
            "position": "MF",
            "nationality": "VIE",
            "kit": "6",
            "achievement": "",
            "name": "Lương Xuân Trường",
            "birthDay": "1995-04-28",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/HPFC_VN0002248_LuongXuanTruong_8-310x467.jpg"
        },
        {   
            "PlayerId": 13,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "168",
            "weight": "65",
            "position": "DF",
            "nationality": "VIE",
            "kit": "23",
            "achievement": "",
            "name": "Nguyễn Thanh Nhân",
            "birthDay": "2000-10-25",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/03/PVFCA_11_NguyenThanhNhan_VN0000558-310x414.jpg"
        },
        {   
            "PlayerId": 14,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "169",
            "weight": "68",
            "position": "MF",
            "nationality": "VIE",
            "kit": "60",
            "achievement": "",
            "name": "Võ Đình Lâm",
            "birthDay": "2000-01-10",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2020/01/HAGL_60_VoDinhLam_VN0001157-310x414.jpg"
        },
        {
            "PlayerId": 15,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "188",
            "weight": "73",
            "position": "MF",
            "nationality": "VIE",
            "kit": "27",
            "achievement": "",
            "name": "Nguyễn Văn Triệu",
            "birthDay": "2003-01-17",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_21_NguyenVanTrieu_VN0001163-310x414.jpg"
        },
        {
            "PlayerId": 16,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "Naturalization Player",
            "height": "186",
            "weight": "80",
            "position": "MF",
            "nationality": "KR",
            "kit": "40",
            "achievement": "",
            "name": "An Sae Hee",
            "birthDay": "1991-02-08",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/07/HAGL-40-An-Sae-Hee-310x413.jpg"
        },
        {   
            "PlayerId": 17,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "169",
            "weight": "63",
            "position": "ST",
            "nationality": "VIE",
            "kit": "20",
            "achievement": "",
            "name": "Trần Bảo Toàn",
            "birthDay": "2000-07-14",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2019/02/HAGL_20_TranBaoToan_VN0001159-310x414.jpg"
        },
        {   
            "PlayerId": 18,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "Naturalization Player",
            "height": "183",
            "weight": "83",
            "position": "ST",
            "nationality": "BRA",
            "kit": "30",
            "achievement": "",
            "name": "Washington Brandão Dos Santos",
            "birthDay": "1990-08-18",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/12.-BRANDAO-310x431.jpg"
        },
        {   
            "PlayerId": 19,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "174",
            "weight": "70",
            "position": "MF",
            "nationality": "VIE",
            "kit": "24",
            "achievement": "",
            "name": "Nguyễn Đức Việt",
            "birthDay": "2004-01-01",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_24_NguyenDucViet_VN001697-310x551.jpg"
        },
        {
            "PlayerId": 20,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "172",
            "weight": "73",
            "position": "DF",
            "nationality": "VIE",
            "kit": "17",
            "achievement": "",
            "name": "Vũ Văn Thanh",
            "birthDay": "1996-04-14",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/CAHN_17_VuVanThanh_VN001905-310x413.jpg"
        },
        {
            "PlayerId": 21,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "168",
            "weight": "65",
            "position": "MF",
            "nationality": "VIE",
            "kit": "21",
            "achievement": "",
            "name": "Lê Huy Kiệt",
            "birthDay": "2003-10-20",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_VN0000452_LEHUYKIET_21.jpg"
        },
        {   
            "PlayerId": 22,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "170",
            "weight": "70",
            "position": "DF",
            "nationality": "VIE",
            "kit": "5",
            "achievement": "",
            "name": "Trần Hữu Đông Triều",
            "birthDay": "1995-08-20",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_5_TranHuuDongTrieu_VN0001160-310x414.jpg"
        },
        {   
            "PlayerId": 23,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "178",
            "weight": "70",
            "position": "DF",
            "nationality": "VIE",
            "kit": "15",
            "achievement": "",
            "name": "Nguyễn Hữu Tuấn",
            "birthDay": "1992-05-06",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2023/10/HUE_15_NguyenHuuTuan_VN001486.jpg"
        },
        {   
            "PlayerId": 24,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "169",
            "weight": "64",
            "position": "DF",
            "nationality": "VIE",
            "kit": "2",
            "achievement": "",
            "name": "Lê Văn Sơn",
            "birthDay": "1996-12-20",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/2.-LÊ-VĂN-SƠN-310x422.jpg"
        },
        {   
            "PlayerId": 25,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "172",
            "weight": "60",
            "position": "ST",
            "nationality": "VIE",
            "kit": "47",
            "achievement": "",
            "name": "Cao Hoàng Tú",
            "birthDay": "2001-06-09",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/DNFC_11_CaoHoangTu_VN001349-310x413.jpg"
        },
        {   
            "PlayerId": 26,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "175",
            "weight": "66",
            "position": "MF",
            "nationality": "VIE",
            "kit": "11",
            "achievement": "",
            "name": "Nguyễn Tuấn Anh",
            "birthDay": "1995-05-16",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2020/01/HPFC_79_NguyenTuanAnh_VN001684-310x461.png"
        },
        {
            "PlayerId": 27,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "174",
            "weight": "67",
            "position": "MF",
            "nationality": "VIE",
            "kit": "82",
            "achievement": "",
            "name": "A Hoàng",
            "birthDay": "1995-07-31",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2018/12/HAGL_71_AHoang_VN0001168-310x414.jpg"
        },
        {
            "PlayerId": 28,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "177",
            "weight": "73",
            "position": "GK",
            "nationality": "VIE",
            "kit": "1",
            "achievement": "",
            "name": "Dương Văn Lợi",
            "birthDay": "2000-12-02",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/1.-DƯƠNG-VĂN-LỢI-310x420.jpg"
        },
        {
            "PlayerId": 29,
            "clubName": "LPBank Hoàng Anh Gia Lai",
            "seaSon": "2023-2024",
            "typePlayer": "National Player",
            "height": "169",
            "weight": "63",
            "position": "ST",
            "nationality": "VIE",
            "kit": "22",
            "achievement": "",
            "name": "Nguyễn Nhĩ Khang",
            "birthDay": "2001-02-16",
            "status": "",
            "PlayerImg": "https://vpf.vn/wp-content/uploads/2022/02/HAGL_VN0000453_NGUYENNHIKHANG_22.jpg"
        }
    ]
};