export const matchesData = [
  {
    logo1: "https://upload.wikimedia.org/wikipedia/vi/thumb/2/21/H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg/1200px-H%E1%BA%A3i_Ph%C3%B2ng_FC_2021.svg.png",
    logo2: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg',
    datetime: '20 Tháng 10, 2023 18:00',
    stadium: 'SVĐ Lạch Tray',
    homeTeam: 'Hải Phòng',
    awayTeam: 'LPBank Hoàng Anh Gia Lai',
    scoreteam1: '1',
    scoreteam2: '1',
    attendance: '15000 người',
    turn: '1',
    id:1,
    season: '2023',
  },
  {
    logo1: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg',
    logo2: 'https://upload.wikimedia.org/wikipedia/commons/f/f0/Logo_LPBank_Hoang_Anh_Gia_Lai.jpg',
    datetime: '21 Tháng 10, 2023 18:00',
    stadium: 'SVĐ Thanh Hóa',
    homeTeam: 'Đông Á Thanh Hóa',
    awayTeam: 'Hồng Lĩnh Hà Tĩnh',
    scoreteam1: '2',
    scoreteam2: '2',
    attendance: '8000 người',
    turn:'2',
    id:2,
    season: '2023',
  }
];
